name: Rain
favicon: null
layout_spectrum: 0.15210178378038108
typography_spectrum: 0.48201884771697223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8090885055717081
  lightness: 0.490346074802801
  saturation: 0.2300958933774382
  rhythmicContrast: 0.5215913755819201
purpose: []
